In [18]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import yellowbrick as yb

from yellowbrick.features.rankd import Rank1D, Rank2D 
from yellowbrick.features.radviz import RadViz 
from yellowbrick.features.pcoords import ParallelCoordinates 
from yellowbrick.features.jointplot import JointPlotVisualizer
from yellowbrick.features.pca import PCADecomposition
from yellowbrick.features.scatter import ScatterVisualizer

In [10]:
data = pd.read_csv("data/forest_fires_clean.csv")
data.head()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_nov,month_oct,month_sep,day_fri,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,7,5,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,1,0,0,0,0,0,0
1,7,4,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,1,0,0,0,0,0,0,1,0
2,7,4,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,1,0,0,0,1,0,0,0,0
3,8,6,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,1,0,0,0,0,0,0
4,8,6,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,0,0,1,0,0,0

###### Description

In [19]:
data.describe()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_nov,month_oct,month_sep,day_fri,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,4.669246,4.299807,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,...,0.001934,0.029014,0.332689,0.164410,0.143133,0.162476,0.183752,0.117988,0.123791,0.104449
std,2.313778,1.229900,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,...,0.043980,0.168007,0.471632,0.371006,0.350548,0.369244,0.387657,0.322907,0.329662,0.306138
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.000000,5.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

###### Data Types

In [20]:
data.dtypes

X              int64
Y              int64
FFMC         float64
DMC          float64
DC           float64
ISI          float64
temp         float64
RH             int64
wind         float64
rain         float64
area         float64
month_apr      int64
month_aug      int64
month_dec      int64
month_feb      int64
month_jan      int64
month_jul      int64
month_jun      int64
month_mar      int64
month_may      int64
month_nov      int64
month_oct      int64
month_sep      int64
day_fri        int64
day_mon        int64
day_sat        int64
day_sun        int64
day_thu        int64
day_tue        int64
day_wed        int64
dtype: object

###### Checking for null values

In [15]:
data.isnull().values.any()

False

In [17]:
data[data.columns[:]].isnull().sum()

X            0
Y            0
FFMC         0
DMC          0
DC           0
ISI          0
temp         0
RH           0
wind         0
rain         0
area         0
month_apr    0
month_aug    0
month_dec    0
month_feb    0
month_jan    0
month_jul    0
month_jun    0
month_mar    0
month_may    0
month_nov    0
month_oct    0
month_sep    0
day_fri      0
day_mon      0
day_sat      0
day_sun      0
day_thu      0
day_tue      0
day_wed      0
dtype: int64

> No null values found. Life is good, perhaps!

In [22]:
print("Correlation:", data.corr(method='pearson'))

Correlation:                   X         Y      FFMC       DMC        DC       ISI  \
X          1.000000  0.539548 -0.021039 -0.048384 -0.085916  0.006210
Y          0.539548  1.000000 -0.046308  0.007782 -0.101178 -0.024488
FFMC      -0.021039 -0.046308  1.000000  0.382619  0.330512  0.531805
DMC       -0.048384  0.007782  0.382619  1.000000  0.682192  0.305128
DC        -0.085916 -0.101178  0.330512  0.682192  1.000000  0.229154
ISI        0.006210 -0.024488  0.531805  0.305128  0.229154  1.000000
temp      -0.051258 -0.024103  0.431532  0.469594  0.496208  0.394287
RH         0.085223  0.062221 -0.300995  0.073795 -0.039192 -0.132517
wind       0.018798 -0.020341 -0.028485 -0.105342 -0.203466  0.106826
rain       0.065387  0.033234  0.056702  0.074790  0.035861  0.067668
area       0.063385  0.044873  0.040122  0.072994  0.049383  0.008258
month_apr  0.063832 -0.008405 -0.117199 -0.197543 -0.268211 -0.106478
month_aug -0.059669 -0.010404  0.228103  0.497928  0.279361  0.334639
month_dec -0.006547  0.075850 -0.137044 -0.176301 -0.105642 -0.162322
month_feb  0.041721  0.016358 -0.281535 -0.317899 -0.399277 -0.249777
month_jan -0.045002  0.010153 -0.454771 -0.105647 -0.115064 -0.103588
month_jul  0.061062  0.061449  0.031833 -0.001946 -0.100887  0.020982
month_jun  0.129616  0.078594 -0.040634 -0.050403 -0.186183  0.111516
month_mar  0.007827  0.050495 -0.074327 -0.407404 -0.650427 -0.143520
month_may  0.008917 -0.015206 -0.037230 -0.081980 -0.114209 -0.060493
month_nov  0.025344 -0.046570 -0.088964 -0.074218 -0.078380 -0.076559
month_oct  0.089545  0.004717 -0.005998 -0.187632  0.093279 -0.071154
month_sep -0.087216 -0.105465  0.076609  0.110907  0.531857 -0.068877
day_fri   -0.020061 -0.048773  0.019306 -0.012010 -0.004220  0.046695
day_mon    0.039367  0.021640 -0.059396 -0.107921 -0.052993 -0.158601
day_sat    0.024461  0.003483 -0.019637 -0.003653 -0.035189 -0.038585
day_sun   -0.029338  0.006172 -0.089517  0.025355 -0.001431 -0.003243
day_thu    0.000457  0.027873  0.071730  0.087672  0.051859 -0.022406
day_tue   -0.027521 -0.053475  0.011225  0.000016  0.028368  0.068610
day_wed    0.016035  0.050495  0.093908  0.017939  0.024803  0.125415

               temp        RH      wind      rain    ...     month_nov  \
X         -0.051258  0.085223  0.018798  0.065387    ...      0.025344
Y         -0.024103  0.062221 -0.020341  0.033234    ...     -0.046570
FFMC       0.431532 -0.300995 -0.028485  0.056702    ...     -0.088964
DMC        0.469594  0.073795 -0.105342  0.074790    ...     -0.074218
DC         0.496208 -0.039192 -0.203466  0.035861    ...     -0.078380
ISI        0.394287 -0.132517  0.106826  0.067668    ...     -0.076559
temp       1.000000 -0.527390 -0.227116  0.069491    ...     -0.053798
RH        -0.527390  1.000000  0.069410  0.099751    ...     -0.035885
wind      -0.227116  0.069410  1.000000  0.061119    ...      0.011864
rain       0.069491  0.099751  0.061119  1.000000    ...     -0.003225
area       0.097844 -0.075519  0.012317 -0.007366    ...     -0.008893
month_apr -0.157051  0.021235  0.048266 -0.009752    ...     -0.005860
month_aug  0.351404  0.054761  0.028577  0.093101    ...     -0.032724
month_dec -0.329648 -0.047714  0.269702 -0.009752    ...     -0.005860
month_feb -0.320015  0.140430 -0.029431 -0.014698    ...     -0.008831
month_jan -0.146520  0.170923 -0.070245 -0.004566    ...     -0.002743
month_jul  0.142588  0.013185 -0.040645 -0.013390    ...     -0.011308
month_jun  0.051015  0.009382  0.012124 -0.013510    ...     -0.008117
month_mar -0.341797 -0.089836  0.181433 -0.020744    ...     -0.015034
month_may -0.045540  0.086822  0.015054 -0.004566    ...     -0.002743
month_nov -0.053798 -0.035885  0.011864 -0.003225    ...      1.000000
month_oct -0.053513 -0.072334 -0.053850 -0.012665    ...     -0.007610
month_sep  0.088006 -0.062596 -0.181476 -0.051733    ...     -0.031083
day_fri   -0.071949  0.064506  0.118090 -0.004261    ...     -0.019527
day_mon   -0.136529  0.009376 -0.063881 -0.029945    ...     -0.017992
day_sat    0.034899 -0.023869 -0.063799 -0.032271    ...     -0.019390
day_sun    0.014403  0.136220  0.027981 -0.017872    ...     -0.020887
day_thu    0.051432 -0.123061 -0.062553 -0.026798    ...     -0.016101
day_tue    0.035630 -0.014211  0.053396  0.139311    ...      0.117121
day_wed    0.090580 -0.087508 -0.019965 -0.020744    ...     -0.015034

           month_oct  month_sep   day_fri   day_mon   day_sat   day_sun  \
X           0.089545  -0.087216 -0.020061  0.039367  0.024461 -0.029338
Y           0.004717  -0.105465 -0.048773  0.021640  0.003483  0.006172
FFMC       -0.005998   0.076609  0.019306 -0.059396 -0.019637 -0.089517
DMC        -0.187632   0.110907 -0.012010 -0.107921 -0.003653  0.025355
DC          0.093279   0.531857 -0.004220 -0.052993 -0.035189 -0.001431
ISI        -0.071154  -0.068877  0.046695 -0.158601 -0.038585 -0.003243
temp       -0.053513   0.088006 -0.071949 -0.136529  0.034899  0.014403
RH         -0.072334  -0.062596  0.064506  0.009376 -0.023869  0.136220
wind       -0.053850  -0.181476  0.118090 -0.063881 -0.063799  0.027981
rain       -0.012665  -0.051733 -0.004261 -0.029945 -0.032271 -0.017872
area       -0.016878   0.056573 -0.052911 -0.021206  0.087868 -0.020463
month_apr  -0.023008  -0.093982 -0.019140 -0.012171 -0.018534  0.051409
month_aug  -0.128493  -0.524858 -0.100837 -0.130774 -0.009808  0.064566
month_dec  -0.023008  -0.093982 -0.019140  0.114519 -0.058625 -0.024966
month_feb  -0.034676  -0.141642  0.046323  0.003933  0.020406  0.008416
month_jan  -0.010772  -0.044001 -0.027643 -0.025470  0.057019  0.050887
month_jul  -0.044402  -0.181367 -0.048969 -0.013300  0.060945 -0.018241
month_jun  -0.031874  -0.130195  0.006000  0.017553 -0.022408  0.024540
month_mar  -0.059034  -0.241135  0.036205  0.077125  0.021024 -0.047726
month_may  -0.010772  -0.044001  0.056423 -0.025470  0.057019 -0.029568
month_nov  -0.007610  -0.031083 -0.019527 -0.017992 -0.019390 -0.020887
month_oct   1.000000  -0.122053 -0.045585  0.060975  0.017584  0.007252
month_sep  -0.122053   1.000000  0.107671  0.039632 -0.032783 -0.048817
day_fri    -0.045585   0.107671  1.000000 -0.181293 -0.195372 -0.210462
day_mon     0.060975   0.039632 -0.181293  1.000000 -0.180015 -0.193919
day_sat     0.017584  -0.032783 -0.195372 -0.180015  1.000000 -0.208978
day_sun     0.007252  -0.048817 -0.210462 -0.193919 -0.208978  1.000000
day_thu    -0.063223   0.008984 -0.162237 -0.149485 -0.161094 -0.173535
day_tue     0.005008  -0.028570 -0.166728 -0.153623 -0.165553 -0.178339
day_wed     0.016325  -0.053222 -0.151487 -0.139579 -0.150419 -0.162036

            day_thu   day_tue   day_wed
X          0.000457 -0.027521  0.016035
Y          0.027873 -0.053475  0.050495
FFMC       0.071730  0.011225  0.093908
DMC        0.087672  0.000016  0.017939
DC         0.051859  0.028368  0.024803
ISI       -0.022406  0.068610  0.125415
temp       0.051432  0.035630  0.090580
RH        -0.123061 -0.014211 -0.087508
wind      -0.062553  0.053396 -0.019965
rain      -0.026798  0.139311 -0.020744
area       0.020121 -0.001333 -0.011452
month_apr  0.043007 -0.050030  0.002899
month_aug  0.053726  0.064061  0.076367
month_dec -0.002838 -0.005125  0.002899
month_feb -0.042278 -0.014491 -0.035713
month_jan -0.022793 -0.023424 -0.021282
month_jul -0.019300  0.049688 -0.008985
month_jun -0.000195 -0.069308  0.043422
month_mar -0.026885 -0.032351 -0.033917
month_may -0.022793 -0.023424 -0.021282
month_nov -0.016101  0.117121 -0.015034
month_oct -0.063223  0.005008  0.016325
month_sep  0.008984 -0.028570 -0.053222
day_fri   -0.162237 -0.166728 -0.151487
day_mon   -0.149485 -0.153623 -0.139579
day_sat   -0.161094 -0.165553 -0.150419
day_sun   -0.173535 -0.178339 -0.162036
day_thu    1.000000 -0.137475 -0.124908
day_tue   -0.137475  1.000000 -0.128365
day_wed   -0.124908 -0.128365  1.000000

[30 rows x 30 columns]